version: '3.8'

services:
  file-sharing-test-asignment:
    image: ghcr.io/typ60pirojok/file-sharing-test-asignment:latest
    container_name: file-sharing-test-asignment
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped